[package]
name = "blackdoc"
version = "0.1.1"
description = "BlackDoc desktop editor"
edition = "2021"

[lib]
name = "blackdoc_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
url = "2"
base64 = "0.22"
regex = "1"
tauri-plugin-updater = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
